# Generated by Django 3.2.4 on 2021-10-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210620_2024"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
