# Generated by Django 3.2.4 on 2021-11-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_generatedpassword_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generatedpassword",
            options={
                "ordering": ["-date", "is_active"],
                "verbose_name": "временный пароль",
                "verbose_name_plural": "временные пароли",
            },
        ),
    ]
