# Generated by Django 3.2.4 on 2021-11-28 15:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_registration_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDeliveryAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locality", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("house", models.PositiveIntegerField()),
                ("block", models.CharField(blank=True, max_length=255, null=True)),
                ("entrance", models.PositiveIntegerField(blank=True, null=True)),
                ("floor", models.PositiveIntegerField(blank=True, null=True)),
                ("apartment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "additional_information",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                                regex="^\\+?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_address",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
