# Generated by Django 3.2.4 on 2021-12-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_customerdeliveryaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
    ]
