# Generated by Django 4.0.1 on 2022-02-02 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_customerdeliveryaddress_is_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
