# Generated by Django 3.2.4 on 2021-11-21 22:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0015_alter_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measure_unit", models.CharField(max_length=35)),
                ("remaining", models.FloatField(default=0)),
                ("min_remaining", models.FloatField(default=0)),
                ("max_remaining", models.FloatField(default=0)),
                ("supplier", models.CharField(max_length=255)),
                ("supplier_email", models.EmailField(max_length=254)),
                (
                    "supplier_phone",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                                regex="^\\+?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tech_card_product",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemainingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remaining", models.FloatField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remaining_product",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
