# Generated by Django 4.0.1 on 2022-03-02 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("production", "0001_initial"),
        ("internal_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productiondocument",
            name="daily_menu_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_documents",
                to="production.dailymenuplan",
                verbose_name="план меню на день",
            ),
        ),
        migrations.AddField(
            model_name="canceldocument",
            name="cancels",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelled_by",
                to="internal_api.primarydocument",
                verbose_name="отменяет",
            ),
        ),
    ]
