# Generated by Django 3.2.4 on 2021-11-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_category_image"),
        ("internal_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="techcard",
            name="amount",
            field=models.FloatField(default=1),
        ),
        migrations.RemoveField(
            model_name="techcard",
            name="product",
        ),
        migrations.AddField(
            model_name="techcard",
            name="product",
            field=models.ManyToManyField(
                related_name="tech_card_product", to="products.Product"
            ),
        ),
    ]
