# Generated by Django 4.0.1 on 2022-03-11 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0002_initial_break_dependency_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(9999.99),
                ],
                verbose_name="Цена",
            ),
        ),
    ]
