# Generated by Django 3.2.4 on 2022-01-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0002_menudishes_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menudishes",
            name="product",
        ),
    ]
