# Generated by Django 3.2.4 on 2022-01-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0003_remove_menudishes_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menudishes",
            name="dish",
        ),
        migrations.RemoveField(
            model_name="menudishes",
            name="menu",
        ),
        migrations.RemoveField(
            model_name="techcard",
            name="author",
        ),
        migrations.RemoveField(
            model_name="techcard",
            name="product",
        ),
        migrations.DeleteModel(
            name="DailyMenuPlan",
        ),
        migrations.DeleteModel(
            name="MenuDishes",
        ),
        migrations.DeleteModel(
            name="TechCard",
        ),
    ]
