# Generated by Django 4.0.1 on 2022-03-11 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0003_warehouse_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(9999.99),
                ],
                verbose_name="Цена",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 0.01), ("price__lte", 9999.99)),
                name="price_range",
            ),
        ),
    ]
