# Generated by Django 3.2.4 on 2021-12-10 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0003_shops_date_added"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Shops",
            new_name="Shop",
        ),
    ]
