# Generated by Django 3.2.4 on 2021-12-11 15:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0004_rename_shops_shop"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMenuPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="remainingproduct",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="remainingproduct",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="techcard",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="techcard",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="techcard",
            name="name",
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="techcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="auto_order",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="margin",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="max_remaining",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="min_remaining",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="remaining",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="supplier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="supplier_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="supplier_phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("position", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                                regex="^\\+?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("date_hired", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working", "Работает"),
                            ("fired", "Уволен"),
                            ("vacation", "Отпуск"),
                            ("maternity_leave", "Декрет"),
                            ("probation", "Исп. срок"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="internal-api/staff/"
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("fathers_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("passport", models.CharField(max_length=100)),
                ("place_of_birth", models.CharField(max_length=255)),
                ("department_issued_passport", models.CharField(max_length=255)),
                ("identification_number", models.CharField(max_length=255)),
                ("date_passport_issued", models.DateField()),
                ("date_passport_valid", models.DateField()),
                ("contract_period", models.IntegerField()),
                ("contract_type", models.CharField(max_length=255)),
                (
                    "working_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="internal_api.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuDishes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="internal_api.techcard",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="internal_api.dailymenuplan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dailymenuplan",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="internal_api.personnel"
            ),
        ),
        migrations.AddField(
            model_name="dailymenuplan",
            name="dishes",
            field=models.ManyToManyField(
                through="internal_api.MenuDishes", to="internal_api.TechCard"
            ),
        ),
        migrations.AddField(
            model_name="techcard",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="internal_api.personnel",
            ),
            preserve_default=False,
        ),
    ]
