# Generated by Django 4.0.1 on 2022-03-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0004_alter_warehouse_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouserecord",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="стоимость",
            ),
        ),
    ]
