# Generated by Django 3.2.4 on 2022-01-24 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0005_techcard"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMenuPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="internal_api.personnel",
                    ),
                ),
                ("dishes", models.ManyToManyField(to="internal_api.TechCard")),
            ],
            options={
                "verbose_name": "План меню на день",
                "verbose_name_plural": "Планы меню на день",
            },
        ),
    ]
