# Generated by Django 3.2.4 on 2021-12-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0005_auto_20211211_1837"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="measure_unit",
        ),
    ]
