# Generated by Django 4.0.1 on 2022-03-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_alter_dailymenuplan_author_alter_techcard_author"),
        ("internal_api", "0005_warehouserecord_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personneldocument",
            name="personnel",
        ),
        migrations.DeleteModel(
            name="Personnel",
        ),
        migrations.DeleteModel(
            name="PersonnelDocument",
        ),
    ]
