# Generated by Django 3.2.4 on 2022-01-24 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0006_dailymenuplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="menu_dish",
                        to="internal_api.techcard",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="internal_api.dailymenuplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка меню на день",
                "verbose_name_plural": "Заявки меню на день",
            },
        ),
    ]
