# Generated by Django 4.0.1 on 2022-03-20 00:12

import django.core.validators
from django.db import migrations, models

import internal_api.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "internal_api",
            "0006_remove_personneldocument_personnel_delete_personnel_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={"verbose_name": "Филиал", "verbose_name_plural": "Филиалы"},
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="payer_identification_number",
        ),
        migrations.AddField(
            model_name="supplier",
            name="taxpayer_identification_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ИНН"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="address",
            field=models.TextField(verbose_name="адрес"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="date_added",
            field=models.DateTimeField(auto_now=True, verbose_name="дата добавления"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="is_archive",
            field=models.BooleanField(default=False, verbose_name="архивный"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=255, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="адрес"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="bank_account",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="номер банковского счета",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="bank_identifier_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="БИК"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="extra_info",
            field=models.JSONField(
                blank=True, null=True, verbose_name="дополнительная информация"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="inner_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="внутренний ID"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="is_archive",
            field=models.BooleanField(default=False, verbose_name="архивный"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=255, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
                verbose_name="номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="supplycontract",
            name="contract",
            field=models.FileField(
                upload_to=internal_api.models.create_contract_download_path,
                verbose_name="контракт",
            ),
        ),
        migrations.AlterField(
            model_name="supplycontract",
            name="contract_date",
            field=models.DateField(verbose_name="дата контракта"),
        ),
        migrations.AlterField(
            model_name="supplycontract",
            name="contract_number",
            field=models.CharField(max_length=255, verbose_name="номер контракта"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="auto_order",
            field=models.BooleanField(
                default=False, verbose_name="автоматический заказ"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="max_remaining",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=7,
                verbose_name="максимальный остаток",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="min_remaining",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=7,
                verbose_name="минимальный остаток",
            ),
        ),
    ]
