# Generated by Django 4.0.1 on 2022-03-23 01:59

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0007_alter_shop_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="payment_deferral",
            field=models.PositiveIntegerField(
                default=0, verbose_name="отсрочка оплаты, дней"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="phone_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=17,
                    validators=[
                        django.core.validators.RegexValidator(
                            message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                            regex="^\\+?\\d{9,15}$",
                        )
                    ],
                    verbose_name="номер телефона",
                ),
                default=list,
                size=None,
                blank=True,
                verbose_name="номера телефонов",
            ),
        ),
    ]
