# Generated by Django 3.2.4 on 2022-01-24 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_auto_20220121_2101"),
        ("internal_api", "0007_menudish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="techcard",
            name="product",
        ),
        migrations.CreateModel(
            name="TechCardProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                    ),
                ),
                (
                    "techcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="internal_api.techcard",
                    ),
                ),
            ],
        ),
    ]
