# Generated by Django 3.2.4 on 2021-12-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_api', '0008_alter_warehouse_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='product',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
