# Generated by Django 3.2.4 on 2022-01-26 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0009_techcardproduct_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailymenuplan",
            name="dishes",
        ),
        migrations.AlterField(
            model_name="techcardproduct",
            name="techcard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="techproduct",
                to="internal_api.techcard",
            ),
        ),
    ]
