# Generated by Django 3.2.4 on 2021-12-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_creation_date'),
        ('internal_api', '0009_alter_warehouse_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse', to='products.product'),
        ),
    ]
