# Generated by Django 4.0.1 on 2022-03-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0009_convert_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="phone",
        ),
    ]
