# Generated by Django 4.0.1 on 2022-03-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0010_remove_supplier_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="наценка, %",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="margin",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
