# Generated by Django 3.2.4 on 2022-01-26 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_auto_20220121_2101"),
        ("internal_api", "0011_auto_20220126_1559"),
    ]

    operations = [
        migrations.RenameField(
            model_name="techcardproduct",
            old_name="weight",
            new_name="quantity",
        ),
        migrations.RemoveField(
            model_name="techcardproduct",
            name="techcard",
        ),
        migrations.AddField(
            model_name="dailymenuplan",
            name="dishes",
            field=models.ManyToManyField(
                through="internal_api.MenuDish", to="internal_api.TechCard"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="payer_identification_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="techcard",
            name="product",
            field=models.ManyToManyField(
                through="internal_api.TechCardProduct", to="products.Product"
            ),
        ),
        migrations.AddField(
            model_name="techcardproduct",
            name="tech_card",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tech_product",
                to="internal_api.techcard",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dailymenuplan",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="daily_menu_plan",
                to="internal_api.personnel",
            ),
        ),
        migrations.AlterField(
            model_name="menudish",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="menu_dish",
                to="internal_api.techcard",
            ),
        ),
        migrations.AlterField(
            model_name="menudish",
            name="menu",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="menu_dish",
                to="internal_api.dailymenuplan",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supplier",
            name="bank_identifier_code",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="techcard",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tech_card",
                to="internal_api.personnel",
            ),
        ),
        migrations.AlterField(
            model_name="techcardproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tech_card_product",
                to="products.product",
            ),
        ),
    ]
