# Generated by Django 3.2.4 on 2021-12-19 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_product_vat_value"),
        ("internal_api", "0011_alter_warehouse_shop"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Подтверждено"),
                            ("delivered", "Уволен"),
                            ("canceled", "Отпуск"),
                            ("dispatched", "Декрет"),
                        ],
                        max_length=255,
                    ),
                ),
                ("supplier", models.CharField(max_length=255)),
                ("price", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WarehouseOrderPositions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                ("bonus", models.IntegerField(default=0)),
                ("special", models.FloatField(default=0)),
                ("flaw", models.FloatField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                    ),
                ),
                (
                    "warehouse_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="internal_api.warehouseorder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="warehouseorder",
            name="order_positions",
            field=models.ManyToManyField(
                through="internal_api.WarehouseOrderPositions", to="products.Product"
            ),
        ),
        migrations.AddField(
            model_name="warehouseorder",
            name="warehouse_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="internal_api.warehouse"
            ),
        ),
    ]
