# Generated by Django 4.0.1 on 2022-03-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0011_alter_warehouse_margin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouseorder",
            name="waybill",
        ),
        migrations.RemoveField(
            model_name="warehouseorder",
            name="waybill_date",
        ),
        migrations.AddField(
            model_name="receiptdocument",
            name="waybill",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="номер накладной"
            ),
        ),
        migrations.AddField(
            model_name="receiptdocument",
            name="waybill_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="дата накладной"
            ),
        ),
    ]
