# Generated by Django 3.2.4 on 2022-01-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0012_auto_20220126_1754"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="bank_identifier_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
