# Generated by Django 4.0.1 on 2022-03-30 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0012_remove_warehouseorder_waybill_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnDocument",
            fields=[
                (
                    "primary_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="return_document",
                        serialize=False,
                        to="internal_api.primarydocument",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="причина"),
                ),
            ],
            options={
                "verbose_name": "Документ возврата",
                "verbose_name_plural": "Документы возврата",
            },
            bases=("internal_api.primarydocument",),
        ),
    ]
