# Generated by Django 3.2.4 on 2021-12-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0013_remove_warehouseorder_warehouse_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouseorder",
            name="price",
        ),
    ]
