# Generated by Django 3.2.4 on 2022-01-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0013_alter_supplier_bank_identifier_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplycontract",
            name="contract",
        ),
    ]
