# Generated by Django 4.0.1 on 2022-04-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0015_shop_e_shop_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(blank=True, null=True, verbose_name="годен до"),
                ),
                (
                    "production_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата производства"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="internal_api.supplier",
                        verbose_name="поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "партия",
                "verbose_name_plural": "партии",
                "default_related_name": "batches",
            },
        ),
        migrations.AddField(
            model_name="warehouserecord",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="internal_api.batch",
                verbose_name="партия",
            ),
        ),
    ]
