# Generated by Django 3.2.4 on 2022-01-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal_api', '0015_filesupplycontract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterModelOptions(
            name='supplycontract',
            options={'verbose_name': 'Контракт поставщика', 'verbose_name_plural': 'Контракты поставщиков'},
        ),
    ]
