# Generated by Django 3.2.4 on 2021-12-22 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0015_alter_warehouseorderpositions_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                                regex="^\\+?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("extra_info", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="warehouseorderpositions",
            name="waybill",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
