# Generated by Django 4.0.1 on 2022-02-02 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import internal_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_api', '0017_rename_filesupplycontract_supplycontractfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel_document', models.FileField(upload_to=internal_api.models.create_personnel_document_download_path)),
                ('document_number', models.CharField(max_length=255)),
                ('document_date', models.DateField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel_document', to='internal_api.personnel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='supplycontract',
            name='contract',
            field=models.FileField(default=django.utils.timezone.now, upload_to=internal_api.models.create_contract_download_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SupplyContractFile',
        ),
    ]
