# Generated by Django 3.2.4 on 2021-12-24 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_product_vat_value"),
        ("internal_api", "0017_auto_20211223_0000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_order",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="warehouse_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_order",
                to="internal_api.warehouseorder",
            ),
        ),
    ]
