# Generated by Django 4.0.1 on 2022-02-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0017_rename_filesupplycontract_supplycontractfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalEntities",
            fields=[
                (
                    "registration_id",
                    models.CharField(
                        max_length=9,
                        primary_key=True,
                        serialize=False,
                        verbose_name="регистрационный номер",
                    ),
                ),
                (
                    "registration_date",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="дата регистрации",
                    ),
                ),
                (
                    "active",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="действует"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="телефон"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="регион"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="имейл"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="адрес"
                    ),
                ),
                (
                    "okved",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ОКВЭД"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="краткое наименование",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="полное наименование",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="статус"
                    ),
                ),
            ],
            options={
                "verbose_name": "Юридическое лицо",
                "verbose_name_plural": "Юридические лица",
                "db_table": "legal_entities",
                "managed": False,
            },
        ),
    ]
