# Generated by Django 4.0.1 on 2022-02-11 15:20

import django.db.models.deletion
from django.db import migrations, models

import internal_api.models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0017_rename_filesupplycontract_supplycontractfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalEntities",
            fields=[
                (
                    "registration_id",
                    models.CharField(
                        max_length=9,
                        primary_key=True,
                        serialize=False,
                        verbose_name="регистрационный номер",
                    ),
                ),
                (
                    "registration_date",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="дата регистрации",
                    ),
                ),
                (
                    "active",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="действует"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="телефон"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="регион"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="имейл"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="адрес"
                    ),
                ),
                (
                    "okved",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ОКВЭД"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="краткое наименование",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="полное наименование",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="статус"
                    ),
                ),
            ],
            options={
                "verbose_name": "Юридическое лицо",
                "verbose_name_plural": "Юридические лица",
                "db_table": "legal_entities",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PersonnelDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personnel_document",
                    models.FileField(
                        null=True,
                        upload_to=internal_api.models.create_personnel_document_download_path,
                    ),
                ),
                ("document_number", models.CharField(max_length=255)),
                ("document_date", models.DateField()),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personnel_document",
                        to="internal_api.personnel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="supplycontract",
            name="contract",
            field=models.FileField(
                default=1, upload_to=internal_api.models.create_contract_download_path
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="remainingproduct",
            name="remaining",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name="techcard",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name="techcardproduct",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="margin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="max_remaining",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="min_remaining",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="remaining",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse",
                to="internal_api.shop",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="buying_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="flaw",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="margin",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="special",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="value_added_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="value_added_tax_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.DeleteModel(
            name="SupplyContractFile",
        ),
    ]
