# Generated by Django 3.2.4 on 2021-12-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0018_auto_20211224_0309"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shop",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="techcard",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="warehouseorder",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
    ]
