# Generated by Django 4.0.1 on 2022-02-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_measurementunit_remove_product_measure_unit_and_more"),
        ("internal_api", "0018_legalentities_personneldocument_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menudish",
            name="dish",
        ),
        migrations.RemoveField(
            model_name="menudish",
            name="menu",
        ),
        migrations.RemoveField(
            model_name="remainingproduct",
            name="product",
        ),
        migrations.RemoveField(
            model_name="techcard",
            name="author",
        ),
        migrations.RemoveField(
            model_name="techcard",
            name="product",
        ),
        migrations.RemoveField(
            model_name="techcardproduct",
            name="product",
        ),
        migrations.RemoveField(
            model_name="techcardproduct",
            name="tech_card",
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={
                "default_related_name": "warehouses",
                "verbose_name": "Запас",
                "verbose_name_plural": "Запасы",
            },
        ),
        migrations.AlterModelOptions(
            name="warehouseorderpositions",
            options={
                "default_related_name": "warehouse_order_positions",
                "verbose_name": "Строка заказа",
                "verbose_name_plural": "Строки заказа",
            },
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="product",
        ),
        migrations.RemoveField(
            model_name="warehouseorderpositions",
            name="product",
        ),
        migrations.AddField(
            model_name="warehouse",
            name="product_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.productunit"
            ),
        ),
        migrations.AddField(
            model_name="warehouseorderpositions",
            name="product_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.productunit"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="internal_api.shop"
            ),
        ),
        migrations.AlterField(
            model_name="warehouseorder",
            name="order_positions",
            field=models.ManyToManyField(
                blank=True,
                through="internal_api.WarehouseOrderPositions",
                to="products.ProductUnit",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_orders",
                to="internal_api.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="warehouse_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="internal_api.warehouseorder",
            ),
        ),
        migrations.DeleteModel(
            name="DailyMenuPlan",
        ),
        migrations.DeleteModel(
            name="MenuDish",
        ),
        migrations.DeleteModel(
            name="RemainingProduct",
        ),
        migrations.DeleteModel(
            name="TechCard",
        ),
        migrations.DeleteModel(
            name="TechCardProduct",
        ),
    ]
