# Generated by Django 4.0.1 on 2022-04-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0018_remove_warehouse_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="max_remaining",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=9,
                verbose_name="максимальный остаток",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="min_remaining",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=9,
                verbose_name="минимальный остаток",
            ),
        ),
        migrations.AlterField(
            model_name="warehouserecord",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4, max_digits=9, verbose_name="количество"
            ),
        ),
    ]
