# Generated by Django 4.0.1 on 2022-02-03 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0018_legalentities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remainingproduct",
            name="remaining",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name="techcard",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name="techcardproduct",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="margin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="max_remaining",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="min_remaining",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="remaining",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse",
                to="internal_api.shop",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="buying_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="flaw",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="margin",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="special",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="value_added_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="value_added_tax_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
