# Generated by Django 4.0.1 on 2022-02-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0018_personneldocument_supplycontract_contract_and_more"),
        ("internal_api", "0019_alter_remainingproduct_remaining_and_more"),
    ]

    operations = []
