# Generated by Django 3.2.4 on 2021-12-28 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0019_auto_20211225_1449"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="supplier_email",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="supplier_phone",
        ),
        migrations.AddField(
            model_name="warehouseorder",
            name="order_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="warehouseorderpositions",
            name="buying_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse",
                to="internal_api.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("approving", "Подтверждается"),
                    ("delivered", "Доставлен"),
                    ("canceled", "Отменен"),
                    ("dispatched", "Отправлен"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="warehouseorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_order",
                to="internal_api.supplier",
            ),
        ),
    ]
