# Generated by Django 4.0.1 on 2022-02-17 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0019_remove_menudish_dish_remove_menudish_menu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="remaining",
        ),
        migrations.CreateModel(
            name="WarehouseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="количество"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_records",
                        to="internal_api.warehouse",
                        verbose_name="запас",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изменение запаса",
                "verbose_name_plural": "Изменения запаса",
            },
        ),
    ]
