# Generated by Django 4.0.1 on 2022-02-17 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0020_remove_warehouse_remaining_warehouserecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimaryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "number",
                    models.CharField(max_length=255, unique=True, verbose_name="номер"),
                ),
            ],
            options={
                "verbose_name": "Документ первичного учёта",
                "verbose_name_plural": "Документы первичного учёта",
                "ordering": ("created_at", "number"),
            },
        ),
        migrations.AddField(
            model_name="warehouserecord",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="internal_api.primarydocument",
                verbose_name="первичный документ",
                null=True,
                blank=True,
            ),
            preserve_default=False,
        ),
    ]
