# Generated by Django 3.2.4 on 2021-12-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0020_auto_20211229_0237"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseorderpositions",
            name="value_added_tax",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="warehouseorderpositions",
            name="value_added_tax_value",
            field=models.FloatField(default=0),
        ),
    ]
