# Generated by Django 3.2.4 on 2022-01-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_category_is_archive"),
        ("internal_api", "0021_auto_20211229_0256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseorder",
            name="order_positions",
            field=models.ManyToManyField(
                blank=True,
                through="internal_api.WarehouseOrderPositions",
                to="products.Product",
            ),
        ),
    ]
