# Generated by Django 4.0.1 on 2022-02-17 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0021_primarydocument_warehouserecord_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouserecord",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="internal_api.primarydocument",
                verbose_name="первичный документ",
            ),
        ),
    ]
