# Generated by Django 4.0.5 on 2022-07-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0021_remove_warehouse_duplicates"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("shop", "product_unit"), name="unique_product_unit_and_shop"
            ),
        ),
    ]
