# Generated by Django 4.0.1 on 2022-02-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
        ("internal_api", "0022_alter_warehouserecord_document"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warehouserecord",
            options={
                "default_related_name": "warehouse_records",
                "verbose_name": "Изменение запаса",
                "verbose_name_plural": "Изменения запаса",
            },
        ),
        migrations.AlterField(
            model_name="warehouserecord",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="internal_api.warehouse",
                verbose_name="запас",
            ),
        ),
        migrations.CreateModel(
            name="ProductionDocument",
            fields=[
                (
                    "primarydocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="internal_api.primarydocument",
                    ),
                ),
                (
                    "daily_menu_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_documents",
                        to="production.dailymenuplan",
                        verbose_name="план меню на день",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ учёта произведённой продукции",
                "verbose_name_plural": "Документы учёта произведённой продукции",
            },
            bases=("internal_api.primarydocument",),
        ),
    ]
