# Generated by Django 3.2.4 on 2022-01-04 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_category_is_archive"),
        ("internal_api", "0022_alter_warehouseorder_order_positions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseorderpositions",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_order_product",
                to="products.product",
            ),
        ),
    ]
