# Generated by Django 4.0.6 on 2022-07-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_api', '0022_warehouse_unique_product_unit_and_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledocument',
            name='amount_time',
            field=models.IntegerField(default=0, verbose_name='Количество времени'),
        ),
    ]
