# Generated by Django 4.0.1 on 2022-02-24 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("internal_api", "0023_productiondocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionDocument",
            fields=[
                (
                    "primary_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="conversion_document",
                        serialize=False,
                        to="internal_api.primarydocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ перевода единиц хранения",
                "verbose_name_plural": "Документы перевода единиц хранения",
            },
            bases=("internal_api.primarydocument",),
        ),
        migrations.CreateModel(
            name="InventoryDocument",
            fields=[
                (
                    "primary_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="inventory_document",
                        serialize=False,
                        to="internal_api.primarydocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток на начало периода",
                "verbose_name_plural": "Остатки на начало периода",
            },
            bases=("internal_api.primarydocument",),
        ),
        migrations.CreateModel(
            name="MoveDocument",
            fields=[
                (
                    "primary_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="move_document",
                        serialize=False,
                        to="internal_api.primarydocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ перемещения",
                "verbose_name_plural": "Документы перемещения",
            },
            bases=("internal_api.primarydocument",),
        ),
        migrations.CreateModel(
            name="SaleDocument",
            fields=[
                (
                    "primary_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="sale_document",
                        serialize=False,
                        to="internal_api.primarydocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ продажи",
                "verbose_name_plural": "Документы продажи",
            },
            bases=("internal_api.primarydocument",),
        ),
        migrations.CreateModel(
            name="WriteOffDocument",
            fields=[
                (
                    "primary_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="write_off_document",
                        serialize=False,
                        to="internal_api.primarydocument",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="причина"),
                ),
            ],
            options={
                "verbose_name": "Документ списания",
                "verbose_name_plural": "Документы списания",
            },
            bases=("internal_api.primarydocument",),
        ),
        migrations.AddField(
            model_name="primarydocument",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.CreateModel(
            name="ReceiptDocument",
            fields=[
                (
                    "primary_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="receipt_document",
                        serialize=False,
                        to="internal_api.primarydocument",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="internal_api.warehouseorder",
                        verbose_name="заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ поступления товара",
                "verbose_name_plural": "Документы поступления товара",
            },
            bases=("internal_api.primarydocument",),
        ),
        migrations.CreateModel(
            name="CancelDocument",
            fields=[
                (
                    "primary_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cancel_document",
                        serialize=False,
                        to="internal_api.primarydocument",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="причина"),
                ),
                (
                    "cancels",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_by",
                        to="internal_api.primarydocument",
                        verbose_name="отменяет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ отмены",
                "verbose_name_plural": "Документы отмены",
            },
            bases=("internal_api.primarydocument",),
        ),
        migrations.RenameField(
            model_name="ProductionDocument",
            old_name="primarydocument_ptr",
            new_name="primary_document",
        ),
    ]
