# Generated by Django 3.2.4 on 2022-01-16 23:03

import django.db.models.deletion
from django.db import migrations, models

import internal_api.models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0024_warehouseorder_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="bank_account",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="bank_identifier_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="warehouseorder",
            name="waybill_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="warehouseorderpositions",
            name="margin",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="SupplyContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract_number", models.CharField(max_length=255)),
                (
                    "contract",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=internal_api.models.create_contract_download_path,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="internal_api.supplier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
