# Generated by Django 3.2.4 on 2022-01-16 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0025_auto_20220117_0203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplycontract",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supply_contract",
                to="internal_api.supplier",
            ),
        ),
    ]
