# Generated by Django 3.2.4 on 2022-01-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_api", "0026_alter_supplycontract_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="inner_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="supplycontract",
            name="contract_date",
            field=models.DateField(default="2022-03-21"),
            preserve_default=False,
        ),
    ]
