# Generated by Django 3.2.4 on 2021-07-04 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Новостной раздел"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "новостной раздел",
                "verbose_name_plural": "новостные разделы",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Заголовок"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "publication_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата публикации"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        default="Общее",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="news.section",
                        verbose_name="Новостной раздел",
                    ),
                ),
            ],
            options={
                "verbose_name": "новость",
                "verbose_name_plural": "новости",
            },
        ),
    ]
