# Generated by Django 3.2.4 on 2021-07-04 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='section',
            field=models.ForeignKey(default='Общее', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='news', to='news.section', verbose_name='Новостной раздел'),
        ),
    ]
