# Generated by Django 3.2.4 on 2021-12-07 22:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="publication_date",
        ),
        migrations.AddField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
    ]
