# Generated by Django 3.2.4 on 2021-12-10 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_auto_20211208_1630"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="news.section",
                verbose_name="Новостной раздел",
            ),
        ),
    ]
