# Generated by Django 4.0.1 on 2022-02-14 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_section_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='news/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])], verbose_name='Изображение'),
        ),
    ]
