# Generated by Django 4.0.6 on 2022-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='permission',
            field=models.PositiveIntegerField(choices=[(0, 'Для всех'), (1, 'Для онлайн пользователей'), (2, 'Для оффлайн пользователей'), (3, 'Для работников')], default=0, verbose_name='permission'),
        ),
    ]
