# Generated by Django 4.0.6 on 2022-07-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_rename_news_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleparagraph',
            options={'ordering': ('order',), 'verbose_name': 'Параграф', 'verbose_name_plural': 'Параграфы'},
        ),
        migrations.AddField(
            model_name='articleparagraph',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='List order'),
        ),
    ]
