# Generated by Django 4.0.1 on 2022-03-16 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import personnel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "internal_api",
            "0006_remove_personneldocument_personnel_delete_personnel_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("position", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                                regex="^\\+?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("date_hired", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working", "Работает"),
                            ("fired", "Уволен"),
                            ("vacation", "Отпуск"),
                            ("maternity_leave", "Декрет"),
                            ("probation", "Исп. срок"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="internal-api/staff/"
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("fathers_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("passport", models.CharField(max_length=100)),
                ("place_of_birth", models.CharField(max_length=255)),
                ("department_issued_passport", models.CharField(max_length=255)),
                ("identification_number", models.CharField(max_length=255)),
                ("date_passport_issued", models.DateField()),
                ("date_passport_valid", models.DateField()),
                ("contract_period", models.IntegerField()),
                ("contract_type", models.CharField(max_length=255)),
                ("is_archive", models.BooleanField(default=False)),
                (
                    "working_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="internal_api.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонал",
                "verbose_name_plural": "Персонал",
            },
        ),
        migrations.CreateModel(
            name="PersonnelDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personnel_document",
                    models.FileField(
                        null=True,
                        upload_to=personnel.models.create_personnel_document_download_path,
                    ),
                ),
                ("document_number", models.CharField(max_length=255)),
                ("document_date", models.DateField()),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personnel_document",
                        to="personnel.personnel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
