# Generated by Django 4.0.1 on 2022-03-17 03:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "internal_api",
            "0006_remove_personneldocument_personnel_delete_personnel_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="наименование"
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
            },
        ),
        migrations.AlterModelOptions(
            name="personnel",
            options={
                "default_related_name": "personnel",
                "verbose_name": "Личная карточка",
                "verbose_name_plural": "Личные карточки",
            },
        ),
        migrations.AlterModelOptions(
            name="personneldocument",
            options={
                "verbose_name": "Документ работника",
                "verbose_name_plural": "Документы работников",
            },
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="date_hired",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="date_passport_issued",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="date_passport_valid",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="department_issued_passport",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="fathers_name",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="identification_number",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="is_archive",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="is_archived",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="passport",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="place_of_birth",
        ),
        migrations.RemoveField(
            model_name="personnel",
            name="working_place",
        ),
        migrations.RemoveField(
            model_name="personneldocument",
            name="personnel",
        ),
        migrations.AddField(
            model_name="personnel",
            name="hired_at",
            field=models.DateTimeField(auto_now=True, verbose_name="дата найма"),
        ),
        migrations.AddField(
            model_name="personnel",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="workplaces",
            field=models.ManyToManyField(
                to="internal_api.Shop", verbose_name="рабочие места"
            ),
        ),
        migrations.RenameField(
            model_name="personneldocument",
            old_name="document_date",
            new_name="date",
        ),
        migrations.AlterField(
            model_name="personneldocument",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="дата"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personneldocument",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="personnel_documents",
                to="personnel.personnel",
                verbose_name="работник",
            ),
        ),
        migrations.RenameField(
            model_name="personneldocument",
            old_name="document_number",
            new_name="number",
        ),
        migrations.AlterField(
            model_name="personneldocument",
            name="number",
            field=models.CharField(max_length=255, verbose_name="номер"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personnel",
            name="contract_period",
            field=models.IntegerField(verbose_name="срок действия договора"),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="contract_type",
            field=models.CharField(max_length=255, verbose_name="тип договора"),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="phone_number",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
                verbose_name="телефон",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="internal-api/staff/",
                verbose_name="фото",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="status",
            field=models.CharField(
                choices=[
                    ("working", "Работает"),
                    ("fired", "Уволен"),
                    ("vacation", "Отпуск"),
                    ("maternity_leave", "Декрет"),
                    ("probation", "Испытательный срок"),
                    ("archived", "Архивный"),
                ],
                default="probation",
                max_length=255,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="personneldocument",
            name="personnel_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=personnel.models.create_personnel_document_download_path,
                verbose_name="файл документа",
            ),
        ),
        migrations.CreateModel(
            name="LocalPassport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="действителен"),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="фамилия")),
                (
                    "patronymic",
                    models.CharField(max_length=255, verbose_name="отчество"),
                ),
                ("date_of_birth", models.DateField(verbose_name="дата рождения")),
                (
                    "place_of_birth",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="место рождения",
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        max_length=14, unique=True, verbose_name="личный номер"
                    ),
                ),
                (
                    "issued_by",
                    models.CharField(
                        max_length=255, verbose_name="орган, выдавший паспорт"
                    ),
                ),
                ("issued_at", models.DateField(verbose_name="дата выдачи")),
                ("valid_until", models.DateField(verbose_name="срок действия")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_passports",
                        to="personnel.personnel",
                        verbose_name="работник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Паспорт",
                "verbose_name_plural": "Паспорты",
                "ordering": ("issued_by",),
            },
        ),
        migrations.AlterField(
            model_name="personnel",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="personnel.position",
                verbose_name="должность",
            ),
        ),
    ]
