# Generated by Django 4.0.1 on 2022-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0002_position_alter_personnel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localpassport",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="отчество"
            ),
        ),
    ]
