# Generated by Django 4.0.1 on 2022-06-07 17:05

import datetime

from django.db import migrations, models

import discounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="duration",
            field=models.DurationField(
                default=datetime.timedelta, verbose_name="срок действия"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="schedule",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[discounts.models.crontab_string],
                verbose_name="расписание",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="ended_at",
            field=models.DateTimeField(
                default=discounts.models.tz_max, verbose_name="доступно до"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="started_at",
            field=models.DateTimeField(
                default=discounts.models.tz_min, verbose_name="доступно с"
            ),
        ),
    ]
