# Generated by Django 4.0.1 on 2022-03-02 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0028_measurementunit_remove_product_measure_unit_and_more"),
        ("internal_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMenuPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="название")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="internal_api.personnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "План меню на день",
                "verbose_name_plural": "Планы меню на день",
                "default_related_name": "daily_menu_plans",
            },
        ),
        migrations.CreateModel(
            name="TechCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="наименование")),
                ("is_archive", models.BooleanField(default=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=7, verbose_name="выход"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tech_card",
                        to="internal_api.personnel",
                        verbose_name="автор",
                    ),
                ),
                (
                    "end_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="end_products",
                        to="products.productunit",
                        verbose_name="готовый продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Техкарта",
                "verbose_name_plural": "Техкарты",
            },
        ),
        migrations.CreateModel(
            name="TechCardProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="количество"
                    ),
                ),
                (
                    "product_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="products.productunit",
                        verbose_name="сырьё",
                    ),
                ),
                (
                    "tech_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tech_products",
                        to="production.techcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.AddField(
            model_name="techcard",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="ingredients",
                through="production.TechCardProduct",
                to="products.ProductUnit",
                verbose_name="ингредиенты",
            ),
        ),
        migrations.CreateModel(
            name="MenuDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.techcard",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.dailymenuplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка меню на день",
                "verbose_name_plural": "Заявки меню на день",
                "default_related_name": "menu_dishes",
            },
        ),
        migrations.AddField(
            model_name="dailymenuplan",
            name="dishes",
            field=models.ManyToManyField(
                through="production.MenuDish", to="production.TechCard"
            ),
        ),
        migrations.AddField(
            model_name="dailymenuplan",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="internal_api.shop"
            ),
        ),
    ]
