# Generated by Django 4.0.1 on 2022-03-16 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailymenuplan",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="techcard",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tech_card",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
    ]
