# Generated by Django 4.0.1 on 2022-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_alter_dailymenuplan_author_alter_techcard_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="techcard",
            name="appearance",
            field=models.TextField(blank=True, null=True, verbose_name="внешний вид"),
        ),
        migrations.AddField(
            model_name="techcard",
            name="consistence",
            field=models.TextField(blank=True, null=True, verbose_name="консистенция"),
        ),
        migrations.AddField(
            model_name="techcard",
            name="cooking_method",
            field=models.TextField(
                blank=True, null=True, verbose_name="технология приготовления"
            ),
        ),
        migrations.AddField(
            model_name="techcard",
            name="number",
            field=models.CharField(
                blank=True, max_length=255, unique=True, verbose_name="номер"
            ),
        ),
        migrations.AddField(
            model_name="techcard",
            name="regulatory_law",
            field=models.CharField(
                default="СТБ 1210-2010", max_length=255, verbose_name="ТНПА"
            ),
        ),
        migrations.AddField(
            model_name="techcard",
            name="short_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="короткое наименование",
            ),
        ),
        migrations.AddField(
            model_name="techcard",
            name="storage_conditions",
            field=models.TextField(
                blank=True, null=True, verbose_name="условия хранения"
            ),
        ),
        migrations.AddField(
            model_name="techcard",
            name="taste_and_smell",
            field=models.TextField(blank=True, null=True, verbose_name="вкус и запах"),
        ),
        migrations.AddField(
            model_name="techcardproduct",
            name="gross_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=8,
                null=True,
                verbose_name="вес брутто, кг",
            ),
        ),
        migrations.AddField(
            model_name="techcardproduct",
            name="net_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=8,
                null=True,
                verbose_name="вес нетто, кг",
            ),
        ),
        migrations.AlterField(
            model_name="techcard",
            name="amount",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                max_digits=8,
                verbose_name="выход в складских единицах",
            ),
        ),
        migrations.AlterField(
            model_name="techcardproduct",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=8,
                verbose_name="количество в складских единицах",
            ),
        ),
    ]
