# Generated by Django 4.0.1 on 2022-06-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_techcard_appearance_techcard_consistence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymenuplan",
            name="is_prepared",
            field=models.BooleanField(default=False, verbose_name="приготовлено"),
        ),
        migrations.AddField(
            model_name="dailymenuplan",
            name="preparation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="дата приготовления"
            ),
        ),
    ]
