# Generated by Django 3.2.4 on 2021-12-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_auto_20211128_1912"),
    ]

    operations = [
        migrations.AddField(
            model_name="star",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
