# Generated by Django 3.2.4 on 2021-10-09 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория рецептов',
                'verbose_name_plural': 'категории рецептов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('publication_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('other_ingredients', models.TextField(blank=True, null=True, verbose_name='Прочие ингриндиенты')),
                ('cook_time', models.IntegerField(verbose_name='Время приготовления')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='Белки')),
                ('carbohydrates', models.FloatField(blank=True, null=True, verbose_name='Углеводы')),
                ('fats', models.FloatField(blank=True, null=True, verbose_name='Жиры')),
                ('calories', models.FloatField(blank=True, null=True, verbose_name='Калорийность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ingredients_in_stock', models.ManyToManyField(related_name='recipes', to='products.Product', verbose_name='Ингриндиенты в наличии')),
                ('recipe_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.recipecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ['name'],
                'unique_together': {('name', 'recipe_category')},
            },
        ),
    ]
