# Generated by Django 3.2.4 on 2021-11-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(default=1, verbose_name="Порции"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="recipe/", verbose_name="Изображение"
            ),
        ),
    ]
