# Generated by Django 3.2.4 on 2021-07-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategory',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('name', 'recipe_category')},
        ),
    ]
