# Generated by Django 3.2.4 on 2021-11-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_productimages_product"),
        ("recipes", "0002_auto_20211106_0347"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients_in_stock",
        ),
        migrations.CreateModel(
            name="RecipeProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField(default=1)),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Ингриндиенты",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_products",
                        to="recipes.recipe",
                        verbose_name="рецепт",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.RecipeProducts",
                to="products.Product",
                verbose_name="Ингриндиенты в наличии",
            ),
        ),
    ]
