# Generated by Django 3.2.4 on 2021-07-04 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210705_0203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20210705_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_in_stock',
            field=models.ManyToManyField(related_name='recipes', to='products.Product', verbose_name='Ингриндиенты в наличии'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.recipecategory', verbose_name='Категория'),
        ),
    ]
