# Generated by Django 3.2.4 on 2021-11-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211107_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeproducts',
            options={'verbose_name': 'ингриндиент для рецепта', 'verbose_name_plural': 'ингриндиенты для рецепта'},
        ),
        migrations.RenameField(
            model_name='recipeproducts',
            old_name='products',
            new_name='product',
        ),
    ]
