# Generated by Django 3.2.4 on 2021-12-07 22:53

import datetime

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_auto_20211107_1638"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="publication_date",
        ),
        migrations.AddField(
            model_name="recipe",
            name="cooking_steps",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=["1", "2", "3"], size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 12, 7, 22, 53, 22, 460048, tzinfo=utc),
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
