# Generated by Django 3.2.4 on 2021-12-07 23:30

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_auto_20211208_0153"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipecategory",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="recipe/categories/",
                verbose_name="Изображение категории рецепта",
            ),
        ),
        migrations.AddField(
            model_name="recipecategory",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipecategory",
            name="lft",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipecategory",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="recipes.recipecategory",
                verbose_name="Родительская категория",
            ),
        ),
        migrations.AddField(
            model_name="recipecategory",
            name="rght",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipecategory",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
