# Generated by Django 3.2.4 on 2021-12-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_auto_20211208_1630"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="cooking_steps",
        ),
        migrations.CreateModel(
            name="RecipeCookingSteps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="recipe/steps/")),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_steps",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
    ]
