# Generated by Django 3.2.4 on 2021-12-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_auto_20211212_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipecategory",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
    ]
