# Generated by Django 4.0.1 on 2022-02-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_auto_20211225_1449"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="calories",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Калорийность",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="carbohydrates",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Углеводы",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="fats",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Жиры",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="protein",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Белки",
            ),
        ),
        migrations.AlterField(
            model_name="recipeproducts",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
