# Generated by Django 4.0.1 on 2022-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_alter_recipecategory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="carbohydrates",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Углеводы",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="fats",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Жиры",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="protein",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Белки",
            ),
        ),
    ]
