# Generated by Django 3.2.4 on 2021-12-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("processing", "В обработке"),
                    ("in_transit", "В пути"),
                    ("delivered", "Доставлено"),
                    ("canceled", "Отменен"),
                ],
                max_length=75,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card_pre", "Картой на сайте"),
                    ("card_post", "Картой курьеру"),
                    ("cash", "Наличные курьеру"),
                ],
                max_length=10,
            ),
        ),
    ]
