# Generated by Django 3.2.4 on 2021-12-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211206_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('canceled', 'Отменен')], default='processing', max_length=75),
        ),
    ]
