# Generated by Django 3.2.4 on 2021-12-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_auto_20211208_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sum_total",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
