# Generated by Django 4.0.6 on 2022-07-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_is_archive"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
