# Generated by Django 4.0.6 on 2022-07-10 20:15

import django.db.models.deletion
from django.db import migrations, models

import utils.models_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "discounts",
            "0002_offer_duration_offer_schedule_alter_offer_ended_at_and_more",
        ),
        ("orders", "0010_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimaryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=255, unique=True, verbose_name="номер"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="создан"),
                ),
            ],
            options={
                "db_table": "internal_api_primarydocument",
                "ordering": ("created_at", "number"),
                "managed": False,
            },
            bases=(utils.models_utils.SuperclassMixin, models.Model),
        ),
        migrations.CreateModel(
            name="WarehouseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=9, verbose_name="количество"
                    ),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True,
                        db_column="cost",
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="цена со скидками",
                    ),
                ),
            ],
            options={
                "db_table": "internal_api_warehouserecord",
                "managed": False,
                "default_related_name": "lines",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "primary_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="e_shop_order",
                        serialize=False,
                        to="orders.primarydocument",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("processing", "В обработке"),
                            ("in-transit", "В пути"),
                            ("delivered", "Доставлен"),
                            ("canceled", "Отменен"),
                        ],
                        default="new",
                        max_length=15,
                        verbose_name="статус",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card-pre", "Картой на сайте"),
                            ("card-post", "Картой курьеру"),
                            ("cash", "Наличные курьеру"),
                        ],
                        max_length=15,
                        verbose_name="способ оплаты",
                    ),
                ),
                (
                    "buyer_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="примечание покупателя"
                    ),
                ),
                (
                    "staff_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="примечание исполнителя"
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "default_related_name": "orders",
            },
            bases=("orders.primarydocument",),
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "warehouse_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="order_line",
                        serialize=False,
                        to="orders.warehouserecord",
                    ),
                ),
                (
                    "full_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "строка заказа",
                "verbose_name_plural": "строки заказа",
            },
            bases=("orders.warehouserecord",),
        ),
        migrations.CreateModel(
            name="OrderLineOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apply_times",
                    models.PositiveIntegerField(verbose_name="число применений"),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_line_offers",
                        to="discounts.offer",
                        verbose_name="скидка",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="orders.orderline",
                        verbose_name="строка заказа",
                    ),
                ),
            ],
            options={
                "verbose_name": "применённая скидка",
                "verbose_name_plural": "применённые скидки",
            },
        ),
    ]
