# Generated by Django 4.0.6 on 2022-07-17 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_order_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='общая сумма')),
                ('result', models.JSONField(default=dict, editable=False)),
                ('payment_status', models.SmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_result', to='orders.order')),
            ],
            options={
                'verbose_name': 'Результат платежа',
                'verbose_name_plural': 'Результаты платежей',
                'db_table': 'payment_results',
            },
        ),
    ]
