# Generated by Django 3.2.4 on 2021-10-09 22:57

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="", verbose_name="Основное изображение"
                    ),
                ),
                (
                    "protein",
                    models.FloatField(blank=True, null=True, verbose_name="Белки"),
                ),
                (
                    "carbohydrates",
                    models.FloatField(blank=True, null=True, verbose_name="Углеводы"),
                ),
                ("fats", models.FloatField(blank=True, null=True, verbose_name="Жиры")),
                (
                    "calories",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Калорийность"
                    ),
                ),
                (
                    "barcode",
                    models.IntegerField(blank=True, null=True, verbose_name="Штрихкод"),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Страна происхождения",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Срок годности"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Вес (грамм)"
                    ),
                ),
                ("in_stock", models.BooleanField(verbose_name="Наличие")),
                (
                    "own_production",
                    models.BooleanField(
                        default=False, verbose_name="Собственное производство"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "images",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="products.productimages",
                        verbose_name="Изображения товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "unique_together": {("manufacturer", "name")},
            },
        ),
    ]
