# Generated by Django 3.2.4 on 2021-06-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(default=models.CharField(max_length=50, unique=True), max_length=250, unique=True)),
                ('specification', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='Белки')),
                ('carbs', models.FloatField(blank=True, null=True, verbose_name='Углеводы')),
                ('fats', models.FloatField(blank=True, null=True, verbose_name='Жиры')),
                ('calories', models.FloatField(blank=True, null=True, verbose_name='Калорийность')),
                ('barcode', models.IntegerField(blank=True, null=True, verbose_name='Штрихкод')),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True, verbose_name='Производитель')),
                ('origin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна происхождения')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='Рейтинг')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес')),
                ('in_stock', models.BooleanField(verbose_name='Наличие')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'unique_together': {('manufacturer', 'name')},
            },
        ),
    ]
