# Generated by Django 3.2.4 on 2021-10-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Скидка'),
        ),
    ]
