# Generated by Django 3.2.4 on 2021-10-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.IntegerField(blank=True, null=True, verbose_name="Скидка, %"),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.FloatField(blank=True, null=True, verbose_name="Вес, грамм"),
        ),
    ]
