# Generated by Django 3.2.4 on 2021-10-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211010_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image',
            new_name='image_1000',
        ),
        migrations.AddField(
            model_name='productimages',
            name='image_150',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image_500',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
