# Generated by Django 3.2.4 on 2021-10-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_auto_20211014_0253"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="extra_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
