# Generated by Django 3.2.4 on 2021-11-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_auto_20211102_1909"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Основное изображение",
            ),
        ),
    ]
