# Generated by Django 3.2.4 on 2021-11-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_productimages_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/categories/",
                verbose_name="Изображение категории",
            ),
        ),
    ]
