# Generated by Django 3.2.4 on 2021-11-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="products/categories/",
                verbose_name="Изображение категории",
            ),
        ),
    ]
