# Generated by Django 3.2.4 on 2021-12-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
    ]
