# Generated by Django 3.2.4 on 2021-12-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_product_measure_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="creation_date",
        ),
    ]
