# Generated by Django 3.2.4 on 2021-12-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_remove_product_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vat_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
