# Generated by Django 3.2.4 on 2021-12-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_product_vat_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
    ]
