# Generated by Django 4.0.1 on 2022-02-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_auto_20220121_2101"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("manufacturer", "name", "barcode")},
        ),
    ]
