# Generated by Django 4.0.1 on 2022-02-03 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_alter_product_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="for_own_production",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="for_scales",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="short_name",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Краткое наименование",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(9999.99),
                ],
                verbose_name="Цена",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 0.01), ("price__lte", 9999.99)),
                name="price_range",
            ),
        ),
    ]
