# Generated by Django 4.0.1 on 2022-02-03 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_product_for_own_production_product_for_scales_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="calories",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Калорийность",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="carbohydrates",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Углеводы",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="energy",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Энергетическая ценность",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fats",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Жиры",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(9999.99),
                ],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="protein",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Белки",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="vat_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Вес, грамм",
            ),
        ),
    ]
