# Generated by Django 4.0.1 on 2022-02-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0026_alter_product_calories_alter_product_carbohydrates_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Скидка, %",
            ),
        ),
    ]
