# Generated by Django 4.0.1 on 2022-02-15 11:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0027_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="products/categories/",
                validators=[
                    django.core.validators.FileExtensionValidator(["svg", "png", "jpg"])
                ],
                verbose_name="Изображение категории",
            ),
        ),
        migrations.CreateModel(
            name="MeasurementUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="наименование"
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерения",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="measure_unit",
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="products/categories/",
                validators=[
                    django.core.validators.FileExtensionValidator(["svg", "png", "jpg"])
                ],
                verbose_name="Изображение категории",
            ),
        ),
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "for_resale",
                    models.BooleanField(default=True, verbose_name="допустима продажа"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="products.product",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_units",
                        to="products.measurementunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица хранения",
                "verbose_name_plural": "Единицы хранения",
            },
        ),
    ]
