# Generated by Django 4.0.1 on 2022-02-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_measurementunit_remove_product_measure_unit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="множитель"
                    ),
                ),
                (
                    "source_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_sources",
                        to="products.productunit",
                        verbose_name="из",
                    ),
                ),
                (
                    "target_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_targets",
                        to="products.productunit",
                        verbose_name="в",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод единиц хранения",
                "verbose_name_plural": "Переводы единиц хранения",
                "unique_together": {("source_unit", "target_unit")},
            },
        ),
    ]
