# Generated by Django 4.0.1 on 2022-03-11 00:20

from django.db import ProgrammingError, migrations


class RemoveConstraintIfPresent(migrations.RemoveConstraint):
    """
    PostgreSQL can not add constraint (0025) and remove it in one transaction,
    so I have to resort to this hack.
    """

    def database_forwards(self, *args, **kwargs):
        try:
            super().database_forwards(*args, **kwargs)
        except ProgrammingError:
            pass


class Migration(migrations.Migration):

    atomic = False  # important

    dependencies = [
        ("products", "0031_move_prices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        RemoveConstraintIfPresent(
            model_name="product",
            name="price_range",
        ),
    ]
