# Generated by Django 4.0.1 on 2022-03-18 16:46

from django.db import migrations, models
from mptt.fields import TreeForeignKey


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0033_alter_product_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="for_own_production",
        ),
        migrations.AlterField(
            model_name="product",
            name="extra_info",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="дополнительная информация",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_archive",
            field=models.BooleanField(default=False, verbose_name="в архиве"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_sorted",
            field=models.BooleanField(
                default=False,
                verbose_name="завизировано после автоматического добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="vat_value",
            field=models.DecimalField(
                blank=True,
                null=True,
                decimal_places=2,
                max_digits=7,
                verbose_name="НДС, %",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=TreeForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="products",
                to="products.category",
                verbose_name="Категория",
            ),
        ),
    ]
