# Generated by Django 4.0.1 on 2022-03-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0034_remove_product_for_own_production"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "parent"), ("name", "lft", "rght")},
        ),
    ]
