# Generated by Django 4.0.1 on 2022-04-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0036_alter_product_vat_value"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "parent"),
                name="unique_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent", None)),
                fields=("name",),
                name="unique_root_name",
            ),
        ),
    ]
