# Generated by Django 4.0.1 on 2022-04-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0037_alter_category_unique_together_category_unique_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productunit",
            name="for_weighing_scales",
            field=models.BooleanField(
                default=False, verbose_name="для чекопечатающих весов"
            ),
        ),
    ]
