# Generated by Django 4.0.1 on 2022-04-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0038_productunit_for_weighing_scales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="expiration_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="production_date",
        ),
    ]
