# Generated by Django 4.0.1 on 2022-04-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0039_remove_product_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productunit",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=9,
                null=True,
                verbose_name="вес с упаковкой, г",
            ),
        ),
    ]
