# Generated by Django 4.0.1 on 2022-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0040_alter_productunit_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="productunit",
            name="packing_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=9,
                null=True,
                verbose_name="вес упаковки, г",
            ),
        ),
    ]
