# Generated by Django 4.0.1 on 2022-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0041_productunit_packing_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="carbohydrates",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Углеводы",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fats",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Жиры",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="protein",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Белки",
            ),
        ),
    ]
