# Generated by Django 4.0.5 on 2022-06-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0043_refactor_productimage"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("main", True)),
                fields=("product", "main"),
                name="one_main_image_per_product",
            ),
        ),
    ]
