# Generated by Django 4.0.5 on 2022-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_enforce_one_main_image_per_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_excisable',
            field=models.BooleanField(default=False),
        ),
    ]
