# Generated by Django 4.0.5 on 2022-07-12 09:33

import django.core.validators
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_category_is_excisable'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_svg',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='products/categories/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='изображение категории для мобильных'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_excisable',
            field=models.BooleanField(default=False, verbose_name='Подакцизный'),
        ),
    ]
